# Generated by Django 5.2.5 on 2025-08-22 17:23

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position dans le texte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Mention',
                'verbose_name_plural': 'Mentions',
                'db_table': 'post_mentions',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280, verbose_name='Contenu')),
                ('post_type', models.CharField(choices=[('original', 'Post original'), ('retweet', 'Retweet'), ('quote', 'Quote tweet'), ('reply', 'Réponse')], default='original', max_length=10, verbose_name='Type de post')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('retweets_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de retweets')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de réponses')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Post épinglé')),
                ('allow_replies', models.BooleanField(default=True, verbose_name='Autoriser les réponses')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Contenu sensible')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('location_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programmé pour')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Post Hashtag',
                'verbose_name_plural': 'Posts Hashtags',
                'db_table': 'post_hashtags',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('gif', 'GIF')], max_length=10, verbose_name='Type de média')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='posts/images/', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Vidéo')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Média de post',
                'verbose_name_plural': 'Médias de posts',
                'db_table': 'post_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de posts')),
                ('trending_score', models.FloatField(default=0.0, verbose_name='Score de tendance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Hashtag',
                'verbose_name_plural': 'Hashtags',
                'db_table': 'hashtags',
                'ordering': ['-posts_count'],
                'indexes': [models.Index(fields=['name'], name='hashtags_name_33a019_idx'), models.Index(fields=['-posts_count'], name='hashtags_posts_c_ab49d5_idx'), models.Index(fields=['-trending_score'], name='hashtags_trendin_e6680c_idx')],
            },
        ),
    ]
