# Generated by Django 5.2.5 on 2025-08-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0001_initial'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_management.mediafile', verbose_name='Fichier média'),
        ),
    ]
