# Generated by Django 5.2.5 on 2025-08-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('daily', 'Digest quotidien'), ('weekly', 'Digest hebdomadaire'), ('monthly', 'Digest mensuel')], max_length=20, verbose_name='Type de lot')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Lot de notifications',
                'verbose_name_plural': 'Lots de notifications',
                'db_table': 'notification_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_email', models.BooleanField(default=True, verbose_name='Likes par email')),
                ('likes_push', models.BooleanField(default=True, verbose_name='Likes push')),
                ('comments_email', models.BooleanField(default=True, verbose_name='Commentaires par email')),
                ('comments_push', models.BooleanField(default=True, verbose_name='Commentaires push')),
                ('retweets_email', models.BooleanField(default=True, verbose_name='Retweets par email')),
                ('retweets_push', models.BooleanField(default=True, verbose_name='Retweets push')),
                ('follows_email', models.BooleanField(default=True, verbose_name='Nouveaux followers par email')),
                ('follows_push', models.BooleanField(default=True, verbose_name='Nouveaux followers push')),
                ('mentions_email', models.BooleanField(default=True, verbose_name='Mentions par email')),
                ('mentions_push', models.BooleanField(default=True, verbose_name='Mentions push')),
                ('quotes_email', models.BooleanField(default=True, verbose_name='Quote tweets par email')),
                ('quotes_push', models.BooleanField(default=True, verbose_name='Quote tweets push')),
                ('replies_email', models.BooleanField(default=True, verbose_name='Réponses par email')),
                ('replies_push', models.BooleanField(default=True, verbose_name='Réponses push')),
                ('system_email', models.BooleanField(default=True, verbose_name='Notifications système par email')),
                ('system_push', models.BooleanField(default=False, verbose_name='Notifications système push')),
                ('digest_frequency', models.CharField(choices=[('never', 'Jamais'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=20, verbose_name='Fréquence du digest')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début heures silencieuses')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin heures silencieuses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, verbose_name='Endpoint')),
                ('p256dh_key', models.CharField(max_length=100, verbose_name='Clé P256DH')),
                ('auth_key', models.CharField(max_length=50, verbose_name='Clé Auth')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'appareil")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Dernière utilisation')),
            ],
            options={
                'verbose_name': 'Abonnement Push',
                'verbose_name_plural': 'Abonnements Push',
                'db_table': 'push_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Commentaire'), ('retweet', 'Retweet'), ('follow', 'Nouveau follower'), ('mention', 'Mention'), ('quote', 'Quote tweet'), ('reply', 'Réponse'), ('system', 'Notification système')], max_length=20, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('is_push_sent', models.BooleanField(default=False, verbose_name='Push envoyé')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
